# Generated by Django 5.2.4 on 2025-08-02 10:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(help_text='Current location of the driver', max_length=255)),
                ('pickup_location', models.CharField(help_text='Pickup location for the trip', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Dropoff location for the trip', max_length=255)),
                ('current_cycle_hours', models.FloatField(help_text='Current cycle hours used (0-70 hours for 8-day cycle)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_distance', models.FloatField(blank=True, help_text='Total trip distance in miles', null=True)),
                ('estimated_duration', models.FloatField(blank=True, help_text='Estimated duration in hours', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('mandatory_break', 'Mandatory Break'), ('fuel_stop', 'Fuel Stop'), ('rest_stop', 'Rest Stop'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(help_text='Duration of stop in minutes')),
                ('order', models.IntegerField(help_text='Order of stop in the route')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='eld_api.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HOSViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('daily_driving', 'Daily Driving Limit (11 hours)'), ('daily_duty', 'Daily Duty Limit (14 hours)'), ('cycle_limit', '70-Hour/8-Day Cycle Limit'), ('mandatory_break', 'Mandatory 30-minute Break')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('violation', 'Violation')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos_violations', to='eld_api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('vehicle_miles', models.IntegerField(default=0)),
                ('total_hours', models.FloatField(help_text='Total hours for this log entry')),
                ('driving_time', models.FloatField(default=0, help_text='Driving time in hours')),
                ('on_duty_time', models.FloatField(default=0, help_text='On duty time in hours')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='eld_api.trip')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
